### ISSUE TITLE
Minor warnings of html

### ISSUE THREAD

**Issue by shubhankartrivedi** [shubhankartrivedi/Gita-API#22]
<img width="591" alt="Screenshot 2023-11-08 at 1 36 41 AM" src="https://github.com/shubhankartrivedi/Gita-API/assets/78972053/4d5bace9-c78b-4754-b4fb-9c391fb60fd5">
<img width="572" alt="Screenshot 2023-11-08 at 1 36 52 AM" src="https://github.com/shubhankartrivedi/Gita-API/assets/78972053/ba7ba321-8ffd-4cb5-8bb1-26ef40f352df">
<img width="463" alt="Screenshot 2023-11-08 at 1 37 03 AM" src="https://github.com/shubhankartrivedi/Gita-API/assets/78972053/37b1f32c-c812-4c03-b742-755c72610efc">

**Comment by JohnPark24** [comment]
Hi can I help with this?

**Comment by shubhankartrivedi** [comment]
> Hi can I help with this?

Sure! Fork the repo and pull request to development branch when done.

**Comment by JohnPark24** [comment]
Sorry I'm having trouble where exactly to look. Is this a problem in a JS file?

**Comment by shubhankartrivedi** [comment]
> Sorry I'm having trouble where exactly to look. Is this a problem in a JS file?

This is a nextJS project and you have to find the solution yourself, you will get the error messages on console in /test page.
If you are not familiar with nextJS then you can't fix it.

**Comment by Manish-hr14** [comment]
kindly assign to me..
