### ISSUE TITLE
BUG: Refresh of Ping Status after hover state change

### ISSUE THREAD

**Issue by shubhankartrivedi** [shubhankartrivedi/Gita-API#37]
https://gita.shubhankartrivedi.com/test

When you hover, it will refresh the data which is not needed now.

<img width="411" alt="Screenshot 2023-11-09 at 10 03 53 PM" src="https://github.com/shubhankartrivedi/Gita-API/assets/78972053/f45f6522-2268-4c8b-b217-1ef9dfa52261">

**Comment by Manish-hr14** [comment]
kindly assign to me
